### ISSUE TITLE
RFP Secure Smart Contract Library, discussion and vote. Public tender

### ISSUE THREAD

**Issue by ABurton22** [AntelopeIO/Coalition#2]
Chains to review the details this week and submit comments / concerns this week
UX excluded due to participation in bidding
Douglas + someone from ENF (likely Yves - need confirmation)

ENF Consolidating and posting to group channel

Proposals due for 16. September, timeline ok so far.

Current phase: Questions may be raised, only one question arrived so far.

Process for vendor selection to be determined by Jeff and Kersten by 1st September

4 bidders raised interest, all offers due 16. September

pizza finance
EOS Nation
DeFi Box
Origin adding support
y-knot (opted out)

**Comment by jeffwerner00** [comment]
Vendors to provide several one page documents to outline solution in greater detail

**Comment by jeffwerner00** [comment]
Counter proposal submitted by vendors to reduce scope of RFP
EOS: No
Telos: No
WAX: No
UX: Abstain
