### ISSUE TITLE
IBC Governance

### ISSUE THREAD

**Issue by ABurton22** [AntelopeIO/Coalition#3]
Meeting occurred, begin a list of initial questions to resolve.
Next call on 9/30, continuing ideation

Guillaume to send cal invite to meeting 9/23 noon ET
Guillaume
Ted
Douglas
Lukas

Coordination of a standalone meeting to discuss various topics

fund governance
fund management of all chains

Setup of work group to start work on this package.

**Comment by jeffwerner00** [comment]
Meeting completed on 07 MON.
All items on list covered
Reminder to discuss emergency binder/run book procedures
Guillame shared documentation to Coalition group on TG
